//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.23 at 01:52:31 PM CST 
//


package com.stillhere.pojo;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="YWBS" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="XM" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ZJLX" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ZJHM" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="POLICY_NUM" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="POLICY_NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="HOLDER_NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="INSURANT_NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="POLICY_STATUS" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BANK_NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="POLICY_MOMENY" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="COMPANY_NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="POLICY_STARTDATE" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="POLICY_ENDDATE" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PAID_PREMIUM" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="LSH" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CXSJ" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BXQ" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ZQZHXX")
public class ZQZHXX {

    @XmlAttribute(name = "YWBS", required = true)
    protected String ywbs;
    @XmlAttribute(name = "XM", required = true)
    protected String xm;
    @XmlAttribute(name = "ZJLX", required = true)
    protected String zjlx;
    @XmlAttribute(name = "ZJHM", required = true)
    protected String zjhm;
    @XmlAttribute(name = "POLICY_NUM", required = true)
    protected String policynum;
    @XmlAttribute(name = "POLICY_NAME", required = true)
    protected String policyname;
    @XmlAttribute(name = "HOLDER_NAME", required = true)
    protected String holdername;
    @XmlAttribute(name = "INSURANT_NAME", required = true)
    protected String insurantname;
    @XmlAttribute(name = "POLICY_STATUS", required = true)
    protected String policystatus;
    @XmlAttribute(name = "BANK_NAME", required = true)
    protected String bankname;
    @XmlAttribute(name = "POLICY_MOMENY", required = true)
    protected String policymomeny;
    @XmlAttribute(name = "COMPANY_NAME", required = true)
    protected String companyname;
    @XmlAttribute(name = "POLICY_STARTDATE", required = true)
    protected String policystartdate;
    @XmlAttribute(name = "POLICY_ENDDATE", required = true)
    protected String policyenddate;
    @XmlAttribute(name = "PAID_PREMIUM", required = true)
    protected String paidpremium;
    @XmlAttribute(name = "LSH", required = true)
    protected String lsh;
    @XmlAttribute(name = "CXSJ", required = true)
    protected String cxsj;
    @XmlAttribute(name = "BXQ", required = true)
    protected String bxq;

    /**
     * Gets the value of the ywbs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYWBS() {
        return ywbs;
    }

    /**
     * Sets the value of the ywbs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYWBS(String value) {
        this.ywbs = value;
    }

    /**
     * Gets the value of the xm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXM() {
        return xm;
    }

    /**
     * Sets the value of the xm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXM(String value) {
        this.xm = value;
    }

    /**
     * Gets the value of the zjlx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZJLX() {
        return zjlx;
    }

    /**
     * Sets the value of the zjlx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZJLX(String value) {
        this.zjlx = value;
    }

    /**
     * Gets the value of the zjhm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZJHM() {
        return zjhm;
    }

    /**
     * Sets the value of the zjhm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZJHM(String value) {
        this.zjhm = value;
    }

    /**
     * Gets the value of the policynum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOLICYNUM() {
        return policynum;
    }

    /**
     * Sets the value of the policynum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOLICYNUM(String value) {
        this.policynum = value;
    }

    /**
     * Gets the value of the policyname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOLICYNAME() {
        return policyname;
    }

    /**
     * Sets the value of the policyname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOLICYNAME(String value) {
        this.policyname = value;
    }

    /**
     * Gets the value of the holdername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHOLDERNAME() {
        return holdername;
    }

    /**
     * Sets the value of the holdername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHOLDERNAME(String value) {
        this.holdername = value;
    }

    /**
     * Gets the value of the insurantname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSURANTNAME() {
        return insurantname;
    }

    /**
     * Sets the value of the insurantname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSURANTNAME(String value) {
        this.insurantname = value;
    }

    /**
     * Gets the value of the policystatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOLICYSTATUS() {
        return policystatus;
    }

    /**
     * Sets the value of the policystatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOLICYSTATUS(String value) {
        this.policystatus = value;
    }

    /**
     * Gets the value of the bankname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBANKNAME() {
        return bankname;
    }

    /**
     * Sets the value of the bankname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBANKNAME(String value) {
        this.bankname = value;
    }

    /**
     * Gets the value of the policymomeny property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOLICYMOMENY() {
        return policymomeny;
    }

    /**
     * Sets the value of the policymomeny property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOLICYMOMENY(String value) {
        this.policymomeny = value;
    }

    /**
     * Gets the value of the companyname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMPANYNAME() {
        return companyname;
    }

    /**
     * Sets the value of the companyname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMPANYNAME(String value) {
        this.companyname = value;
    }

    /**
     * Gets the value of the policystartdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOLICYSTARTDATE() {
        return policystartdate;
    }

    /**
     * Sets the value of the policystartdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOLICYSTARTDATE(String value) {
        this.policystartdate = value;
    }

    /**
     * Gets the value of the policyenddate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOLICYENDDATE() {
        return policyenddate;
    }

    /**
     * Sets the value of the policyenddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOLICYENDDATE(String value) {
        this.policyenddate = value;
    }

    /**
     * Gets the value of the paidpremium property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAIDPREMIUM() {
        return paidpremium;
    }

    /**
     * Sets the value of the paidpremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAIDPREMIUM(String value) {
        this.paidpremium = value;
    }

    /**
     * Gets the value of the lsh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLSH() {
        return lsh;
    }

    /**
     * Sets the value of the lsh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLSH(String value) {
        this.lsh = value;
    }

    /**
     * Gets the value of the cxsj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCXSJ() {
        return cxsj;
    }

    /**
     * Sets the value of the cxsj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCXSJ(String value) {
        this.cxsj = value;
    }

    /**
     * Gets the value of the bxq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBXQ() {
        return bxq;
    }

    /**
     * Sets the value of the bxq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBXQ(String value) {
        this.bxq = value;
    }

}
