//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.23 at 01:52:31 PM CST 
//


package com.stillhere.pojo;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="YWBS" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="XM" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ZJLX" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ZJHM" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="POLICY_NUM" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="POLICY_NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="HOLDER_NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="INSURANT_NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="POLICY_STATUS" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BANK_NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="POLICY_MOMENY" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="COMPANY_NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="POLICY_STARTDATE" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="POLICY_ENDDATE" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PAID_PREMIUM" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="LSH" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CXSJ" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BXQ" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ZQZHXX")
public class ZQZHXX {

    @XmlAttribute(name = "aa", required = true)
    protected String ywbs;
    @XmlAttribute(name = "a", required = true)
    protected String xm;
    @XmlAttribute(name = "aaa", required = true)
    protected String zjlx;

}
